blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.staticfiles.urls import static

from blog.settings import MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sblog/', include('frontblog.urls', namespace='showblog')),
    url(r'^blog/', include('endblog.urls', namespace='editblog')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

endblog/urls.py
from django.conf.urls import url
from endblog import views

urlpatterns = [
    # 注册
    # url(r'^register/', views.register, name='register'),
    # 点击后台管理时看到的登录页面
    url(r'^login/', views.login, name='login'),
    # 登录成功后显示的页面
    url(r'^edit/', views.edit, name='edit'),
    # 点击添加时看到的添加文章页面
    url(r'^add_article/', views.add_article, name='add_article'),
    # 显示文章列表的页面
    url(r'^art_list/', views.art_list, name='art_list'),
    # 删除文章
    url(r'del_art/(\d+)/', views.del_art_id, name='del_art'),
    # 修改文章
    url(r'^edit_art/(\d+)', views.edit_art_id, name='edit_art'),

]

frontblog/urls.py
from django.conf.urls import url
from frontblog import views

urlpatterns = [
    # 用户看到的首页
    url(r'^e_blog/', views.e_blog, name='e_blog'),
    # 点击文章时看到的内容页
    url(r'^e_content/(\d+)/', views.e_content, name='e_content'),
    # 点击关于我时看到的页面
    url(r'^about/', views.about, name='about')
]

endblog/models.py
from django.db import models


# 创建文章模型
class Article(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=300)
    content = models.TextField()
    icon = models.ImageField(upload_to='article', null=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta():
        db_table = 'article'


# 创建登录用户表
class SuperUser(models.Model):
    username = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=16)
    create_time = models.DateTimeField(auto_now_add=True)
    recreate_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'superuser'


# 创建令牌模型
class TokenUser(models.Model):
    token = models.CharField(max_length=30)
    # token和用户表之间是一对一关系
    user = models.OneToOneField(SuperUser)

    class Meta:
        db_table = 'token_user'

frontblog/models.py
from django.db import models

# Create your models here.

endblog/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from endblog.ArtForm import EditArtForm, AddArtForm
from endblog.models import Article, SuperUser

from utils.functions import is_login


# 登录页面
def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('userpwd')
        user = SuperUser.objects.filter(username=username, password=password).first()
        if not user:
            return render(request, 'login.html')

        request.session['user_id'] = user.id
        res = HttpResponseRedirect('/blog/edit/')
        return res


# 登录成功后返回的页面
def edit(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        # 通过Paginator对得到的数据进行切割分页显示
        paginator = Paginator(articles, 5)
        # 获得当前页的页数信息
        page = paginator.page(page)
        return render(request, 'edit.html', {'page': page})


# 添加文章
def add_article(request):
    if request.method == 'GET':
        return render(request, 'add_article.html')
    if request.method == 'POST':
        # 通过ArticleFrom的对象form验证输入的信息是否符合要求
        form = AddArtForm(request.POST, request.FILES)
        # 验证成功，就去获取输入的值，并且保存到数据库中，而后返回文章列表
        if form.is_valid():
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            Article.objects.create(title=title, desc=desc, content=content, icon=icon)
            # 通过reverse返回到由namespace和name拼接的url地址
            return HttpResponseRedirect(reverse('editblog:edit'))
        # 验证失败，将错误信息返回到当前网页，不保存错误的信息，不修改地址，只渲染页面
        else:
            return render(request, 'add_article.html', {'form': form})


# 显示文章
def art_list(request):
    if request.method == 'GET':
        # 分页显示
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        # 通过Paginator对得到的数据进行切割分页显示
        paginator = Paginator(articles, 1)
        # 获得当前页的页数信息
        page = paginator.page(page)
        return render(request, 'art_list.html', {'page': page})


# 删除
def del_art_id(request, id):
    if request.method == 'GET':
        # 在数据库中查询与id匹配的数据，并进行删除
        Article.objects.filter(pk=id).delete()
        return HttpResponseRedirect(reverse('editblog:edit'))


# 修改
def edit_art_id(request, id):
    if request.method == 'GET':
        article = Article.objects.filter(pk=id).first()
        return render(request, 'add_article.html', {'article': article})

    if request.method == 'POST':
        # EditArtForm用作校验
        form = EditArtForm(request.POST, request.FILES)
        if form.is_valid():
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            content = form.cleaned_data['content']
            icon = form.cleaned_data['icon']
            # 表示字段验证成功
            article = Article.objects.filter(pk=id).first()
            article.title = title
            article.desc = desc
            article.content = content
            if icon:
                article.icon = icon
            article.save()
            return HttpResponseRedirect(reverse('editblog:edit'))
        else:
            article = Article.objects.filter(pk=id).first()
            return render(request, 'add_article.html', {'form': form, 'article': article})

frontblog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

from endblog.models import Article


def e_blog(request):
    if request.method == 'GET':
        page = int(request.GET.get('page', 1))
        articles = Article.objects.all()
        # 通过Paginator对得到的数据进行切割分页显示
        paginator = Paginator(articles, 5)
        # 获得当前页的页数信息
        page = paginator.page(page)
        return render(request, 'index.html', {'page': page})


def e_content(request, id):
    if request.method == 'GET':
        articles = Article.objects.filter(pk=id).first()

        return render(request, 'content.html', {'content': articles})


def about(request):
    if request.method == 'GET':
        return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}

{% block title %}
	关于我
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="/static/css/about.css">
{% endblock %}

{% block content %}
	<div class="nav">
		<div class="nav_c">
			<div class="nav_c_logo"><a href="{% url 'showblog:e_blog' %}">小鄂的博客</a></div>
			<div class="nav_c_content">
				<li><a href="{% url 'showblog:e_blog' %}">博客首页</a></li>
			</div>
		</div>
	</div>
	<div class="content">
		<div class="block"></div>
		<div class="mes">
			<a href=""><img src="/static/image/ouwen.gif" alt=""></a>
			<p>
				没什么好说的~~~
			</p>
		</div>
		<div class="call">
			<img src="/static/image/qq(1).jpg" alt="">
			<img src="/static/image/qq(2).jpg" alt="">
		</div>
	</div>
{% endblock %}

templates/add_article.html
{% extends 'base.html' %}

{% block title%}
    添加文章
{% endblock %}

{% block content%}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>标题：<input type="text" name="title" value="{{ article.title }}">{{ form.errors.title }}</p>
        <p>简短描述：<input type="text" name="desc" value="{{ article.desc }}">{{ form.errors.desc }}</p>
        <p>内容：<textarea name="content" id="editor_id">{{ article.content | safe}}</textarea>{{ form.errors.content }}</p>
        <p>首图：<input type="file" name="icon">
            {% if article.icon %}
                <img src="/media/{{ article.icon }}" alt="你大大的错了">
            {% endif %}
        </p>
        <input type="submit" value="提交">
    </form>
{% endblock %}

{% block js %}
    {% load static %}
        <script src="{% static 'kindeditor/kindeditor-all-min.js' %}" type="text/javascript"></script>
        <script src="{% static 'kindeditor/lang/zh-CN.js'%}" type="text/javascript"></script>
        <script type="text/javascript">
            KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
            });
    </script>
{% endblock %}

templates/art_list.html
{% extends 'base.html' %}

{% block title %}
    文章列表
{% endblock %}
{% block css %}
    <link rel="stylesheet" href="/static/css/index.css">
{% endblock %}

{% block content %}
    <div class="nav">
	<div class="nav_c">
		<div class="nav_c_logo"><a href="">小鄂的博客</a></div>
		<div class="nav_c_content">
			<li><a href="{% url 'showblog:e_blog' %}">博客首页</a></li>
			<li><a href="{% url 'showblog:about' %}">关于我</a></li>
			<li><a href="{% url 'editblog:login' %}">后台管理</a></li>
			<li>
				<input type="text" placeholder="搜索"/>
				<input type="button" value="搜索"/>
			</li>
		</div>
	</div>
</div>
<div class="content">
	<div class="main">
		{% for art in page %}
		<li>
			<a href="{% url 'showblog:e_content' art.id %}">
				<img src="/media/{{ art.icon }}" alt="没有上传图片耶">
				<h3>{{ art.title }}</h3>
				<p>&emsp;&emsp;{{ art.desc }}</p>
			</a>
		</li>
		{% endfor %}

	</div>
	<div class="page">
		<p>
			共{{ page.paginator.num_pages }}页，
			当前{{ page.number }}页，
			共{{ page.paginator.count }}条数据

			{% if page.has_previous %}
				<a href="{% url 'showblog:e_blog' %}?page={{ page.previous_page_number }}">上一页</a>
			{% endif %}

			{% for i in page.paginator.page_range %}
				<a href="{% url 'showblog:e_blog' %}?page={{ i }}">{{ i }}</a>
			{% endfor %}

			{% if page.has_next %}
				<a href="{% url 'showblog:e_blog' %}?page={{ page.next_page_number }}">下一页</a>
			{% endif %}

		</p>
	</div>
</div>
<div class="footer"></div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</body>
</html>

templates/content.html
{% extends 'base.html' %}

{% block title %}
    内容
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="/static/css/content.css">
{% endblock %}

{% block content %}
    <div class="nav">
        <div class="nav_c">
            <div class="nav_c_logo"><a href="{% url 'showblog:e_blog' %}">小鄂的博客</a></div>
            <div class="nav_c_content">
                <li><a href="{% url 'showblog:e_blog' %}">博客首页</a></li>
                <li><a href="{% url 'showblog:about' %}">关于我</a></li>
            </div>
        </div>
    </div>
    <div class="content">
        <h1>{{content.title}}</h1>
        <h1>&ensp;</h1>
        <p>{{content.content}}</p>
    </div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}

{% block title %}
    小鄂的博客
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="/static/css/edit.css">
{% endblock %}

{% block content %}
	<div class="nav">
	<div class="nav_c">
		<div class="nav_c_logo"><a href="">小鄂的博客</a></div>
		<div class="nav_c_content">
			<li><a href="{% url 'showblog:e_blog' %}">博客首页</a></li>
			<li><a href="{% url 'showblog:about' %}">关于我</a></li>
			<li><a href="{% url 'editblog:login' %}">后台管理</a></li>
			<li>
				<input type="text" placeholder="搜索"/>
				<input type="button" value="搜索"/>
			</li>
		</div>
	</div>
</div>
<div class="content">
	<div class="main">
		<table>
			<tbody>
				{% for art in page %}
				<tr class="content">
					<td class="content_1">
						<a href="{% url 'showblog:e_content' art.id %}">
							<img src="/media/{{ art.icon }}" alt="没有上传图片耶" class="icon">
							<h3 class="title">{{ art.title }}</h3>
							<p class="desc">&emsp;&emsp;{{ art.desc }}</p>
						</a>
					</td>
					<td class="content_2">
						<p><a href="{% url 'editblog:edit_art' art.id %}">修改文章</a></p>
						<p><a href="{% url 'editblog:add_article' %}">增加文章</a></p>
						<p><a href="{% url 'editblog:del_art' art.id %}">删除文章</a></p>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="page">
		<p>
			共{{ page.paginator.num_pages }}页，
			当前{{ page.number }}页，
			共{{ page.paginator.count }}条数据

			{% if page.has_previous %}
				<a href="{% url 'editblog:edit' %}?page={{ page.previous_page_number }}">上一页</a>
			{% endif %}

			{% for i in page.paginator.page_range %}
				<a href="{% url 'editblog:edit' %}?page={{ i }}">{{ i }}</a>
			{% endfor %}

			{% if page.has_next %}
				<a href="{% url 'editblog:edit' %}?page={{ page.next_page_number }}">下一页</a>
			{% endif %}

		</p>
	</div>
</div>
<div class="footer"></div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
    博客
{% endblock %}

{% block css %}
	<link rel="stylesheet" href="/static/css/index.css">
{% endblock %}

{% block content %}
	<div class="nav">
	<div class="nav_c">
		<div class="nav_c_logo"><a href="">小鄂的博客</a></div>
		<div class="nav_c_content">
			<li><a href="{% url 'showblog:e_blog' %}">博客首页</a></li>
			<li><a href="{% url 'showblog:about' %}">关于我</a></li>
			<li><a href="{% url 'editblog:login' %}">后台管理</a></li>
			<li>
				<input type="text" placeholder="搜索"/>
				<input type="button" value="搜索"/>
			</li>
		</div>
	</div>
</div>
<div class="content">
	<div class="aside">
		<div class="about_me">
			<img src="/static/image/fg.gif" >
			<p><span>小鄂</span>呵呵哒</p>
		</div>
		<div class="calendar">

		</div>
	</div>
	<div class="main">
		{% for art in page %}
		<li>
			<a href="{% url 'showblog:e_content' art.id %}">
				<img src="/media/{{ art.icon }}" alt="没有上传图片耶">
				<h3>{{ art.title }}</h3>
				<p>&emsp;&emsp;{{ art.desc }}</p>
			</a>
		</li>
		{% endfor %}

	</div>
	<div class="page">
		<p>
			共{{ page.paginator.num_pages }}页，
			当前{{ page.number }}页，
			共{{ page.paginator.count }}条数据

			{% if page.has_previous %}
				<a href="{% url 'showblog:e_blog' %}?page={{ page.previous_page_number }}">上一页</a>
			{% endif %}

			{% for i in page.paginator.page_range %}
				<a href="{% url 'showblog:e_blog' %}?page={{ i }}">{{ i }}</a>
			{% endfor %}

			{% if page.has_next %}
				<a href="{% url 'showblog:e_blog' %}?page={{ page.next_page_number }}">下一页</a>
			{% endif %}

		</p>
	</div>
</div>
<div class="footer"></div>
{% endblock %}

templates/login.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>小鄂博客登录</title>

    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">
    <link rel="apple-touch-icon-precomposed" href="images/icon/icon.png">
    <link rel="shortcut icon" href="images/icon/favicon.ico">

    <script src="/static/js/jquery-2.1.4.min.js"></script>
    <!--[if gte IE 9]>
    <script src="/static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/static/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="/static/js/respond.min.js" type="text/javascript"></script>
    <script src="/static/js/selectivizr-min.js" type="text/javascript"></script>
    <![endif]-->
    <!--[if lt IE 9]>
      <script>window.location.href='upgrade-browser.html';</script>
    <![endif]-->
</head>

<body class="user-select">

    <div class="container">
        <div class="siteIcon"><img src="/static/image/ouwen.gif" alt="" data-toggle="tooltip" data-placement="top" title="欢迎进入小鄂的博客" draggable="false" /></div>
        <form method="post" autocomplete="off" class="form-signin">
            <h2 class="form-signin-heading">管理员登录</h2>
            <label for="userName" class="sr-only">用户名</label>
            <input type="text" id="userName" name="username" class="form-control" placeholder="请输入用户名" required autofocus autocomplete="off" maxlength="10">
            <label for="userPwd" class="sr-only">密码</label>
            <input type="password" id="userPwd" name="userpwd" class="form-control" placeholder="请输入密码" required autocomplete="off" maxlength="18">
            <a href="{% url 'editblog:edit' %}"><button class="btn btn-lg btn-primary btn-block" type="submit" id="signinSubmit">登录</button></a>
        </form>

        <div class="footer">
            <p><a href="{% url 'showblog:e_blog' %}" data-toggle="tooltip" data-placement="left" title="不知道自己在哪?">回到博客首页 →</a></p>
        </div>
    </div>
    <script src="/static/js/bootstrap.min.js"></script>
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    window.oncontextmenu = function(){
        //return false;
    };
    $('.siteIcon img').click(function(){
        window.location.reload();
    });
    $('#signinSubmit').click(function(){
        if($('#userName').val() === ''){
            $(this).text('用户名不能为空');
        }else if($('#userPwd').val() === ''){
            $(this).text('密码不能为空');
        }else{
            $(this).text('请稍后...');
        }
    });
    </script>
</body>
</html>

templates/register.html
{% extends 'base.html' %}

{% block title %}
    注册
{% endblock%}

{% block content %}

    {{ err_name }}
    {{ message }}

    <form action="" method="post">
        <p>账号：<input type="text" name="username"></p>
        <p>密码：<input type="password" name="password"></p>
        <p>确认密码：<input type="password" name="password2"></p>
        <p><input type="submit" value="提交"></p>
    </form>
{% endblock%}